apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: server
  name: server
  namespace: default
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    io.kompose.service: server
  type: LoadBalancer
