apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: server
  name: server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: server
  template:
    metadata:
      labels:
        io.kompose.network/qunicorn-core-qunicorn: "true"
        io.kompose.service: server
    spec:
      containers:
        - env:
            - name: CONTAINER_MODE
              value: server
            - name: BROKER_URL
              value: redis://broker:6379
            - name: JWKS_URL
              value: http://keycloak:8081/auth/realms/qunicorn/protocol/openid-connect/certs
            - name: DB_URL
              value: postgresql+psycopg://postgres:passwd@postgres/qunicorn
            - name: SERVER_PORT
              value: "8081"
            - name: NUMBA_CACHE_DIR
              value: /app/cache
          image: ghcr.io/qunicorn/qunicorn-core:main
          name: server
          ports:
            - containerPort: 8081
              hostPort: 8081
              protocol: TCP
      restartPolicy: Always
